version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ghost
    networks:
      - my-network

  ghost:
    depends_on:
      - db
    image: ghost:1-alpine
    ports:
    - "2368:2368"
    restart: always
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
    networks:
      - my-network
  
volumes:
  db_data:

networks:
  my-network: