name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-test:
    name: Deploy to heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Deploy to Heroku cotainers
        uses: heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_NAME}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          usedocker: true
